version: 2

project_name: hoofy

before:
  hooks:
    - go mod tidy
    - go vet ./...

builds:
  - id: hoofy
    main: ./cmd/hoofy/
    binary: hoofy
    ldflags:
      - -s -w
      - -X github.com/HendryAvila/Hoofy/internal/server.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: HendryAvila
    name: Hoofy
  draft: false
  prerelease: auto
  name_template: "v{{ .Version }}"
