version: 2

project_name: hoofy

before:
  hooks:
    - go mod tidy
    - go vet ./...

builds:
  - id: hoofy
    main: ./cmd/hoofy/
    binary: hoofy
    ldflags:
      - -s -w
      - -X github.com/HendryAvila/Hoofy/internal/server.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

brews:
  - repository:
      owner: HendryAvila
      name: homebrew-hoofy
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    directory: Formula
    name: hoofy
    homepage: "https://github.com/HendryAvila/Hoofy"
    description: "Spec-Driven Development MCP Server — persistent memory, adaptive changes, clarity gate"
    license: "MIT"
    install: |
      bin.install "hoofy"
    test: |
      system "#{bin}/hoofy", "--version"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: HendryAvila
    name: Hoofy
  draft: false
  prerelease: auto
  name_template: "v{{ .Version }}"
