package prompts

import (
	"context"

	"github.com/mark3labs/mcp-go/mcp"
)

// BootstrapGuidePrompt serves on-demand documentation for bootstrapping
// existing projects into SDD. This is the "cold" counterpart for the
// reverse-engineer + bootstrap workflow in serverInstructions().
type BootstrapGuidePrompt struct{}

// NewBootstrapGuidePrompt creates a BootstrapGuidePrompt.
func NewBootstrapGuidePrompt() *BootstrapGuidePrompt {
	return &BootstrapGuidePrompt{}
}

// Definition returns the MCP prompt definition for registration.
func (p *BootstrapGuidePrompt) Definition() mcp.Prompt {
	return mcp.NewPrompt("sdd-bootstrap-guide",
		mcp.WithPromptDescription(
			"Workflow for bootstrapping existing projects into SDD. "+
				"Covers sdd_reverse_engineer scanning, sdd_bootstrap artifact generation, "+
				"and important rules for existing project onboarding.",
		),
	)
}

// Handle returns the bootstrap workflow documentation.
func (p *BootstrapGuidePrompt) Handle(_ context.Context, _ mcp.GetPromptRequest) (*mcp.GetPromptResult, error) {
	return &mcp.GetPromptResult{
		Description: "SDD Bootstrap Guide for Existing Projects",
		Messages: []mcp.PromptMessage{
			{
				Role:    mcp.RoleUser,
				Content: mcp.NewTextContent(bootstrapGuideContent),
			},
		},
	}, nil
}

const bootstrapGuideContent = `# SDD Bootstrap Guide for Existing Projects

## When This Applies

When sdd_change is used on a project with NO existing SDD artifacts (no requirements.md,
business-rules.md, or design.md in sdd/), the following behavior applies:

- **Medium/Large changes are BLOCKED** with an error asking the user to run
  sdd_reverse_engineer first
- **Small changes proceed** but include a warning that specs are missing

## Workflow for Existing Projects

When you detect a project has no SDD artifacts (either from the sdd_change block message
or by checking for sdd/ directory contents), follow this workflow:

1. **Scan the project**: Call sdd_reverse_engineer to generate a comprehensive scan report
   - Parameters: detail_level (summary/standard/full), max_tokens, scan_path, max_depth
   - The tool is a READ-ONLY scanner — it does NOT modify any files
   - Returns a structured Markdown report with 9 sections: Project Overview,
     Directory Structure, Tech Stack Evidence, Architecture Evidence,
     Conventions & Style, Data Model Evidence, API Evidence, Prior Decisions,
     Test Evidence
   - Also reports which SDD artifacts already exist (if any)

2. **Analyze the report**: YOU analyze the scan results and generate content for the
   missing SDD artifacts:
   - **requirements.md**: Extract functional and non-functional requirements from what
     the code already does (not aspirational — descriptive)
   - **business-rules.md**: Extract domain terms, facts, constraints from the codebase
   - **design.md**: Document the existing architecture, tech stack, components, data model

3. **Write the artifacts**: Call sdd_bootstrap with the generated content
   - The tool writes ONLY missing artifacts — existing ones are preserved
   - All auto-generated artifacts include a header:
     "> Auto-generated by sdd_reverse_engineer — review and refine as needed"
   - Parameters map to the same fields as sdd_generate_requirements,
     sdd_create_business_rules, and sdd_create_design
   - project_name: Optional — defaults to the directory name

4. **User reviews**: Tell the user to review the generated artifacts and refine them
   - The auto-generated header signals these are starting points, not final specs
   - After review, the change pipeline (sdd_change) will work normally

## Important Rules

- sdd_reverse_engineer is ALWAYS read-only — it never writes files
- sdd_bootstrap writes ONLY missing artifacts — never overwrites existing ones
- Generated content should be DESCRIPTIVE (what the code does today), not ASPIRATIONAL
- Always tell the user these are auto-generated starting points that need review
- After bootstrap, sdd_change works normally (artifact guard passes)
`
